use movieselector;
create table if not exists series (movieID int not null unique,
                                   Action int not null default 0,
                                   Adventure int not null default 0,
                                   Animation int not null default 0,
                                   Comedy int not null default 0,
                                   Crime int not null default 0,
                                   Documentary int not null default 0,
                                   Drama int not null default 0,
                                   Family int not null default 0,
                                   Fantasy int not null default 0,
                                   History int not null default 0,
                                   Horror int not null default 0,
                                   Music int not null default 0,
                                   Mystery int not null default 0,
                                   Romance int not null default 0,
                                   ScienceFiction int not null default 0,
                                   TVMovie int not null default 0,
                                   Thriller int not null default 0,
                                   War int not null default 0,
                                   Western int not null default 0);