create table if not exists series (movieID int not null unique,
                                   imdbID varchar(20),
                                   ActionAdventure int not null default 0,
                                   Animation int not null default 0,
                                   Comedy int not null default 0,
                                   Crime int not null default 0,
                                   Documentary int not null default 0,
                                   Drama int not null default 0,
                                   Family int not null default 0,
                                   Kids int not null default 0,
                                   Mystery int not null default 0,
                                   News int not null default 0,
                                   SciFiFantasy int not null default 0,
                                   Reality int not null default 0,
                                   Soap int not null default 0,
                                   Talk int not null default 0,
                                   War int not null default 0,
                                   Western int not null default 0);