create table userprofile (userID int not null,
                                   Action int,
                                   Adventure int,
                                   Animation int,
                                   Comedy int,
                                   Crime int,
                                   Documentary int,
                                   Drama int,
                                   Family int,
                                   Fantasy int,
                                   History int,
                                   Horror int,
                                   Music int,
                                   Mystery int,
                                   Romance int,
                                   ScienceFiction int,
                                   TVMovie int,
                                   Thriller int,
                                   War int,
                                   Western int,
                                   index uID (userID),
                                   foreign key (userID)
                                        references users(ID)
                                        on delete cascade);